"""Add translations table

Revision ID: b01ff8986e83
Revises: f739704a21b6
Create Date: 2025-07-12 09:53:05.512154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b01ff8986e83"
down_revision = "f739704a21b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translations_category"), "translations", ["category"], unique=False
    )
    op.create_index(op.f("ix_translations_id"), "translations", ["id"], unique=False)
    op.create_index(op.f("ix_translations_key"), "translations", ["key"], unique=False)
    op.create_index(
        op.f("ix_translations_language"), "translations", ["language"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translations_language"), table_name="translations")
    op.drop_index(op.f("ix_translations_key"), table_name="translations")
    op.drop_index(op.f("ix_translations_id"), table_name="translations")
    op.drop_index(op.f("ix_translations_category"), table_name="translations")
    op.drop_table("translations")
    # ### end Alembic commands ###
