"""Initial migration

Revision ID: f739704a21b6
Revises: 
Create Date: 2025-07-11 19:29:04.817072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f739704a21b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scientific_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('growing_time_days', sa.Integer(), nullable=False),
    sa.Column('planting_depth_cm', sa.Float(), nullable=True),
    sa.Column('spacing_cm', sa.Float(), nullable=True),
    sa.Column('row_spacing_cm', sa.Float(), nullable=True),
    sa.Column('best_planting_seasons', sa.JSON(), nullable=True),
    sa.Column('min_temperature_c', sa.Float(), nullable=True),
    sa.Column('max_temperature_c', sa.Float(), nullable=True),
    sa.Column('frost_tolerant', sa.Boolean(), nullable=True),
    sa.Column('expected_yield_per_sqm', sa.Float(), nullable=True),
    sa.Column('harvest_window_days', sa.Integer(), nullable=True),
    sa.Column('sun_requirements', sa.String(length=50), nullable=True),
    sa.Column('water_requirements', sa.String(length=50), nullable=True),
    sa.Column('soil_ph_min', sa.Float(), nullable=True),
    sa.Column('soil_ph_max', sa.Float(), nullable=True),
    sa.Column('market_price_per_kg', sa.Float(), nullable=True),
    sa.Column('storage_life_days', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('growing_notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_crops_id'), 'crops', ['id'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('total_area', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_id'), 'farms', ['id'], unique=False)
    op.create_table('selling_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('first_selling_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('selling_frequency_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('target_crops', sa.JSON(), nullable=True),
    sa.Column('target_quantities', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selling_schedules_id'), 'selling_schedules', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_selling_schedules_id'), table_name='selling_schedules')
    op.drop_table('selling_schedules')
    op.drop_index(op.f('ix_farms_id'), table_name='farms')
    op.drop_table('farms')
    op.drop_index(op.f('ix_crops_id'), table_name='crops')
    op.drop_table('crops')
    # ### end Alembic commands ###
